apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stem-woman
  namespace: production
spec:
  rules:
  - host: api.stem-woman.info
  - http:
      paths:
      - path: /
        backend:
          serviceName: stem-woman
          servicePort: 1500