apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stem-woman
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.stem-woman.info
    secretName: stem-woman-tls-prod
  rules:
    - host: api.stem-woman.info
      http:
        paths:
        - path: /
          backend:
            serviceName: stem-woman
            servicePort: 1500
