apiVersion: v1
kind: Service
metadata:
  name: stem-woman-api
  labels:
    app: stem-woman
    tier: backend
    type: api
    name: api
spec:
  ports:
  - port: 1500
    targetPort: 1500
  selector:
    app: stem-woman
