###
# Adapted from https://medium.com/devsondevs/automate-tls-ssl-certificate-issuance-renewal-part-v-4214cd1deb1e
###

apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: anne.chepkeitany@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}