version: "3.3"
services:
  api:
    build: ./../
    env_file:
      - ./configs.env
      - ./secrets.env
    volumes:
      - "./../application:/www"
    ports:
      - 1500:1500
    command: yarn run dev
    depends_on: 
      - postgres 
  postgres:
    image: postgres:9.6.10-alpine
    ports:
      - 5400:5432
    environment:
       - POSTGRES_PASSWORD=My5@Pwd1234
       - POSTGRES_USER=geek
       - POSTGRES_DB=stem-woman
    volumes:
      - "./tmp/postgres/data:/var/lib/postgresql/data/pgdata"

  